import "server-only";

/**
 * Transcript → Archetype Classification Prompt
 *
 * For a SINGLE interview transcript, decides which archetype (from the
 * archetypes generated by the parent ArchetypeSession) this person best
 * exemplifies — or returns null when no archetype is a credible fit.
 *
 * Used as Phase A of the persona pipeline:
 *   classify(transcript, archetypes) → { archetypeId, confidence, rationale, quotes }
 *
 * Strict JSON. The caller stores the verdict in TranscriptClassification.
 */

export interface ArchetypeSummary {
    id: string;
    name: string;
    kicker?: string | null;
    description: string;
    // A short bullet list reflecting the archetype's defining behaviours /
    // barriers / motivations — built from the archetype's fullContentJson.
    definingTraits: string[];
}

export interface ClassificationPromptContext {
    projectName: string;
    researchStatement: string;
    profileTarget?: string;

    transcript: {
        displayName: string;
        text: string;
    };

    archetypes: ArchetypeSummary[];
}

/**
 * Output shape (returned by the model as JSON):
 *
 *   {
 *     archetypeId: string | null,   // null = Unclassified
 *     archetypeName: string | null, // human-readable echo, ignored if archetypeId set
 *     confidence: number,           // 0..1
 *     rationale: string,            // 1 sentence
 *     supportingQuotes: string[]    // 1-3 verbatim excerpts from the transcript
 *   }
 */
export function buildClassificationPrompt(ctx: ClassificationPromptContext): string {
    const { projectName, researchStatement, profileTarget, transcript, archetypes } = ctx;

    const archetypeBlocks = archetypes
        .map((a, i) => {
            const traits = a.definingTraits.length > 0
                ? a.definingTraits.map(t => `    - ${t}`).join("\n")
                : "    (no defining traits listed)";
            return `### Archetype ${i + 1} — ${a.name}
ID: ${a.id}
${a.kicker ? `Kicker: "${a.kicker}"\n` : ""}Description: ${a.description}
Defining traits:
${traits}`;
        })
        .join("\n\n");

    return `# ROLE
You are a careful research analyst. You read ONE interview transcript and decide which of the project's behavioural archetypes this person most resembles, or flag that no archetype is a credible fit.

# PROJECT CONTEXT
Project: ${projectName}
Research statement: ${researchStatement}
${profileTarget ? `Profile target: ${profileTarget}\n` : ""}
# ARCHETYPES YOU MUST CHOOSE BETWEEN

${archetypeBlocks}

# THE INTERVIEW TRANSCRIPT
Interviewee display name: ${transcript.displayName}

<transcript>
${transcript.text.slice(0, 12000)}${transcript.text.length > 12000 ? "\n\n...[TRUNCATED — transcript continues but cut for prompt length]" : ""}
</transcript>

# YOUR TASK
1. Read the transcript end-to-end.
2. Compare it against each archetype's defining traits.
3. Pick the SINGLE best-fitting archetype, OR return null if none of them is a credible match (i.e. the person's pattern doesn't substantively resemble any archetype). Force-fitting is worse than honestly leaving them Unclassified.
4. Express your confidence on a 0–1 scale:
   - 0.85+ : clear behavioural and motivational alignment with multiple defining traits
   - 0.60–0.85 : substantial fit on the central traits, some divergence
   - 0.40–0.60 : partial fit, several mismatches — borderline
   - < 0.40 : weak fit; prefer to return null
5. Quote 1–3 short excerpts (verbatim, ≤ 30 words each) from the transcript that most directly support your verdict.
6. Write a single-sentence rationale explaining why this archetype fits (or why none do).

# RESPONSE
Respond with a SINGLE JSON object — no prose, no markdown, no code fences:

{
  "archetypeId": "<the id from above, or null>",
  "archetypeName": "<the matching archetype's name, or null>",
  "confidence": <number between 0 and 1>,
  "rationale": "<one short sentence>",
  "supportingQuotes": ["<verbatim quote 1>", "<verbatim quote 2>"]
}

Return null for archetypeId when no archetype is a credible fit. Use the archetype IDs exactly as given above — do NOT invent new IDs.`;
}
// Created by Swapnil Bapat © 2026
