"use client";

import Link from "next/link";
import { ChevronRight, FileText, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function TermsOfUsePage() {
    return (
        <div className="min-h-screen pb-16">
            {/* Hero Header */}
            <div className="relative flex flex-col items-center justify-center mb-12 pt-8 text-center max-w-4xl mx-auto w-full px-4 md:px-6">
                <div className="flex flex-col items-center">
                    <div className="h-16 w-16 bg-primary rounded-md flex items-center justify-center mb-4">
                        <FileText className="h-8 w-8 text-primary-foreground" />
                    </div>
                    <h1 className="text-3xl font-bold text-foreground">
                        Terms of Use
                    </h1>
                    <p className="text-muted-foreground mt-2">
                        Last updated: January 2026
                    </p>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-4xl mx-auto px-4 md:px-6">
                <div className="bg-card border border-border rounded-md p-8 md:p-12">

                    <div className="prose max-w-none">
                        <h2 className="text-xl font-bold text-foreground mb-4">1. Purpose and Scope</h2>
                        <p className="text-muted-foreground mb-6">
                            HPB AI Research Tool ("the Application") is an internal training tool developed for the Health Promotion Board (HPB) Singapore.
                            This Application is designed exclusively for interview rehearsal and question quality analysis purposes.
                            All outputs generated by this Application are <strong>synthetic training data only</strong> and cannot be used to inform
                            research synthesis, conclusions about actual participants, or any official decision-making.
                        </p>

                        <h2 className="text-xl font-bold text-foreground mb-4">2. Authorized Use</h2>
                        <p className="text-muted-foreground mb-4">
                            This Application is for <strong>internal HPB use only</strong>. By accessing and using this Application, you confirm that:
                        </p>
                        <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                            <li>You are an authorized HPB staff member or contractor with legitimate access</li>
                            <li>You will only use this Application for its intended purpose of interview training</li>
                            <li>You will not distribute, share, or expose this Application to external parties</li>
                            <li>You understand that AI-generated content is synthetic and for training purposes only</li>
                        </ul>

                        <h2 className="text-xl font-bold text-foreground mb-4">3. Data Classification and Security</h2>
                        <p className="text-muted-foreground mb-4">
                            Users must comply with all applicable IM8 provisions and data handling requirements:
                        </p>
                        <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                            <li>Do not input data classified higher than <strong>OFFICIAL (CLOSED) / SENSITIVE-NORMAL</strong></li>
                            <li>Do not upload documents containing Personally Identifiable Information (PII) without proper de-identification</li>
                            <li>Ensure all uploaded research materials comply with your project's data classification requirements</li>
                            <li>Report any suspected data breaches immediately to your supervisor and IT Security</li>
                        </ul>

                        <h2 className="text-xl font-bold text-foreground mb-4">4. AI-Generated Content</h2>
                        <p className="text-muted-foreground mb-4">
                            All AI-generated content in this Application:
                        </p>
                        <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                            <li>Is <strong>synthetic and fictional</strong> - it does not represent real individuals or actual research findings</li>
                            <li>May contain inaccuracies, hallucinations, or biased content despite safeguards</li>
                            <li>Should be critically reviewed and fact-checked before any downstream use</li>
                            <li>Cannot be cited as research evidence or used in official reports</li>
                            <li>Is subject to the limitations of generative AI technology</li>
                        </ul>

                        <h2 className="text-xl font-bold text-foreground mb-4">5. User Responsibilities</h2>
                        <p className="text-muted-foreground mb-4">
                            As a user of this Application, you are responsible for:
                        </p>
                        <ul className="list-disc list-inside text-muted-foreground mb-6 space-y-2">
                            <li>Reviewing and verifying all AI-generated output before use</li>
                            <li>Reporting problematic, biased, or harmful AI outputs using the feedback mechanism</li>
                            <li>Not attempting to bypass safety guardrails or extract harmful content</li>
                            <li>Maintaining the confidentiality of project-specific research materials</li>
                            <li>Complying with all HPB policies, guidelines, and ethical standards</li>
                        </ul>

                        <h2 className="text-xl font-bold text-foreground mb-4">6. Intellectual Property</h2>
                        <p className="text-muted-foreground mb-6">
                            This Application and its contents are the property of HPB Singapore and its development partners.
                            Users may not copy, modify, distribute, or create derivative works from this Application without
                            explicit written permission. AI-generated content does not transfer intellectual property rights to users.
                        </p>

                        <h2 className="text-xl font-bold text-foreground mb-4">7. Disclaimer of Warranties</h2>
                        <p className="text-muted-foreground mb-6">
                            This Application is provided "as is" without warranties of any kind. HPB does not guarantee the
                            accuracy, completeness, or reliability of AI-generated content. Users assume all risks associated
                            with their use of the Application and any reliance on its outputs.
                        </p>

                        <h2 className="text-xl font-bold text-foreground mb-4">8. Limitation of Liability</h2>
                        <p className="text-muted-foreground mb-6">
                            HPB and its development partners shall not be liable for any direct, indirect, incidental,
                            consequential, or special damages arising from the use of this Application or reliance on its
                            AI-generated outputs. This includes but is not limited to damages from inaccurate information,
                            data loss, or service interruptions.
                        </p>

                        <h2 className="text-xl font-bold text-foreground mb-4">9. Modifications</h2>
                        <p className="text-muted-foreground mb-6">
                            HPB reserves the right to modify these Terms of Use at any time. Continued use of the Application
                            after modifications constitutes acceptance of the updated terms. Users are encouraged to review
                            these terms periodically.
                        </p>

                        <h2 className="text-xl font-bold text-foreground mb-4">10. Contact Information</h2>
                        <p className="text-muted-foreground mb-6">
                            For questions regarding these Terms of Use or to report issues with the Application, please contact
                            your supervisor or the HPB Digital Transformation team.
                        </p>

                        <div className="mt-8 pt-6 border-t border-border">
                            <p className="text-sm text-muted-foreground italic">
                                By using this Application, you acknowledge that you have read, understood, and agree to be bound
                                by these Terms of Use.
                            </p>
                        </div>
                    </div>

                    <div className="mt-8 flex justify-center">
                        <Link href="/dashboard">
                            <Button className="rounded-md">
                                <ArrowLeft className="h-4 w-4 mr-2" />
                                Back to Dashboard
                            </Button>
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
}
// Created by Swapnil Bapat © 2026
