import { BackLink } from "@/components/layout/back-link"
import { PageHeader } from "@/components/layout/page-header"

export default function TermsPage() {
  return (
    <div className="max-w-[720px] mx-auto pt-6 pb-20">
      <BackLink href="/dashboard" label="Back to Dashboard" />

      <PageHeader
        eyebrow="Legal"
        title="Terms of Use"
        description="Last updated: April 2026"
      />

      <article className="flex flex-col gap-8 text-body text-foreground">
        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Purpose and Scope</h2>
          <p className="text-body-lg text-muted-foreground">
            HPB AI Research Tool (&quot;the Application&quot;) is an internal training tool developed for the Health Promotion Board (HPB) Singapore.
            This Application is designed exclusively for interview rehearsal and question quality analysis purposes.
            All outputs generated by this Application are synthetic training data only and cannot be used to inform
            research synthesis, conclusions about actual participants, or any official decision-making.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Authorized Use</h2>
          <p className="text-body">
            This Application is for internal HPB use only. By accessing and using this Application, you confirm that:
          </p>
          <ul className="list-disc list-inside text-body space-y-2">
            <li>You are an authorized HPB staff member or contractor with legitimate access</li>
            <li>You will only use this Application for its intended purpose of interview training</li>
            <li>You will not distribute, share, or expose this Application to external parties</li>
            <li>You understand that AI-generated content is synthetic and for training purposes only</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Data Classification and Security</h2>
          <p className="text-body">
            Users must comply with all applicable IM8 provisions and data handling requirements:
          </p>
          <ul className="list-disc list-inside text-body space-y-2">
            <li>Do not input data classified higher than OFFICIAL (CLOSED) / SENSITIVE-NORMAL</li>
            <li>Do not upload documents containing Personally Identifiable Information (PII) without proper de-identification</li>
            <li>Ensure all uploaded research materials comply with your project&apos;s data classification requirements</li>
            <li>Report any suspected data breaches immediately to your supervisor and IT Security</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">AI-Generated Content</h2>
          <p className="text-body">
            All AI-generated content in this Application:
          </p>
          <ul className="list-disc list-inside text-body space-y-2">
            <li>Is synthetic and fictional - it does not represent real individuals or actual research findings</li>
            <li>May contain inaccuracies, hallucinations, or biased content despite safeguards</li>
            <li>Should be critically reviewed and fact-checked before any downstream use</li>
            <li>Cannot be cited as research evidence or used in official reports</li>
            <li>Is subject to the limitations of generative AI technology</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">User Responsibilities</h2>
          <p className="text-body">
            As a user of this Application, you are responsible for:
          </p>
          <ul className="list-disc list-inside text-body space-y-2">
            <li>Reviewing and verifying all AI-generated output before use</li>
            <li>Reporting problematic, biased, or harmful AI outputs using the feedback mechanism</li>
            <li>Not attempting to bypass safety guardrails or extract harmful content</li>
            <li>Maintaining the confidentiality of project-specific research materials</li>
            <li>Complying with all HPB policies, guidelines, and ethical standards</li>
          </ul>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Intellectual Property</h2>
          <p className="text-body">
            This Application and its contents are the property of HPB Singapore and its development partners.
            Users may not copy, modify, distribute, or create derivative works from this Application without
            explicit written permission. AI-generated content does not transfer intellectual property rights to users.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Disclaimer of Warranties</h2>
          <p className="text-body">
            This Application is provided &quot;as is&quot; without warranties of any kind. HPB does not guarantee the
            accuracy, completeness, or reliability of AI-generated content. Users assume all risks associated
            with their use of the Application and any reliance on its outputs.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Limitation of Liability</h2>
          <p className="text-body">
            HPB and its development partners shall not be liable for any direct, indirect, incidental,
            consequential, or special damages arising from the use of this Application or reliance on its
            AI-generated outputs. This includes but is not limited to damages from inaccurate information,
            data loss, or service interruptions.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Modifications</h2>
          <p className="text-body">
            HPB reserves the right to modify these Terms of Use at any time. Continued use of the Application
            after modifications constitutes acceptance of the updated terms. Users are encouraged to review
            these terms periodically.
          </p>
        </section>

        <section className="flex flex-col gap-3">
          <h2 className="text-display-3">Contact Information</h2>
          <p className="text-body">
            For questions regarding these Terms of Use or to report issues with the Application, please contact
            your supervisor or the HPB Digital Transformation team.
          </p>
          <p className="text-body text-muted-foreground italic text-sm mt-4">
            By using this Application, you acknowledge that you have read, understood, and agree to be bound
            by these Terms of Use.
          </p>
        </section>
      </article>
    </div>
  )
}
